// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EquipoInfoEntity
    {
        /// <summary>
        /// Initializes a new instance of the EquipoInfoEntity class.
        /// </summary>
        public EquipoInfoEntity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EquipoInfoEntity class.
        /// </summary>
        public EquipoInfoEntity(int? equipoId = default(int?), string web = default(string), string iconoUrl = default(string), string twitter = default(string), string instagram = default(string))
        {
            EquipoId = equipoId;
            Web = web;
            IconoUrl = iconoUrl;
            Twitter = twitter;
            Instagram = instagram;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equipoId")]
        public int? EquipoId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "web")]
        public string Web { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iconoUrl")]
        public string IconoUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "twitter")]
        public string Twitter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "instagram")]
        public string Instagram { get; set; }

    }
}
